version: 2
updates:
# Maintain dependencies for Github Actions
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly

# Maintain dependencies for Ruby
- package-ecosystem: bundler
  directory: "/"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
        - minor
        - patch
  schedule:
    interval: weekly

# Maintain dependencies for Node
- package-ecosystem: npm
  directory: "/"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
        - minor
        - patch
  schedule:
    interval: weekly
