version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rails-skeleton
    container_name: rails-skeleton
    env_file: .env
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/rails_skeleton_development
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgres:17-alpine
    container_name: rails-skeleton-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_skeleton_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
